[package]
name = "ratatat"
version = "0.1.0"
authors = ["harri <0@hclarke.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elsa = { git = "https://github.com/Manishearth/elsa.git" }
srcstr = { git = "https://github.com/hclarke/srcstr.git", branch="main"  }
